name: Create Pull Request

on:
  push:
    branches:
      - main  # The branch where changes are pushed from `infra`

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        run: |
          gh pr create --base "update-from-infra" --head "update-from-infra" --title "Automated PR" --body "Automated pull request from infra repo" --repo preti14-m/application
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
