name: Create PR in Application Repo
on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout LZ-infra repo
      uses: actions/checkout@v3

    - name: Checkout Application repo
      uses: actions/checkout@v3
      with:
        repository: preti14-m/application
        token: ${{ secrets.APP_REPO_PAT }}
        path: application-repo

    - name: Sync Changes
      run: |
        cp -r . application-repo/
        cd application-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Sync changes from LZ-infra repo"
        git push origin main

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.APP_REPO_PAT }}
        base: main
        head: sync-from-lz-infra
        title: 'Automated PR: Sync changes from LZ-infra'
        body: 'This PR is automatically created to sync changes from the LZ-infra repo.'
