name: Create PR in Application Repo

on:
  push:
    branches:
      - main  # Adjust to the branch you want to monitor

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the landing zone repo
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Make changes (ensure files are copied or created)
        run: |
          # Example: Copying files from LZ-infra to application repo
          echo "Hello world"

      - name: Verify files and commit
        run: |
          # List files to ensure changes are present
          ls -al
          
          # Ensure we have files to commit
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Sync from LZ-infra: $COMMIT_MESSAGE" || echo "No changes to commit"
            git push origin "$BRANCH_NAME"
          else
            echo "No files to commit"
          fi

      - name: Create PR in Application Repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO="preti14-m/application"
          curl -X POST https://api.github.com/repos/$REPO/pulls \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "Sync from LZ-infra",
              "head": "'"$BRANCH_NAME"'",
              "base": "main",
              "body": "Automated PR created from LZ-infra changes."
            }'
